### ISSUE TITLE
Misspell in 'examples/1_kloppy_gnn_train.ipynb'

### ISSUE THREAD

**Issue by ThiagoBorges81** [UnravelSports/unravelsports#1]
Hello, Joris.

Quite interesting library you have here. I was taking a look around and found a misspell here:

file location: "examples/1_kloppy_gnn_train.ipynb"

Where the mistake is:

"6.3 Build GNN Model

This GNN Model has the same architecture as described in [A Graph Neural Network Deep-dive into Successful Counterattacks {A. Sahasrabudhe & J. Bekkers}](https://github.com/USSoccerFederation/ussf_ssac_23_soccer_gnn/tree/main)

This exact model can also simply be loaded as:

from unravel.classifiers imoprt CrystalGraphClassifier as shown in [Quick Start Guide](https://github.com/UnravelSports/unravelsports/blob/997ae57ecf024d06818d5476f1e27e27aed36e7f/examples/0_quick_start_guide.ipynb)"

In the last line where you explain how to import CrystalGraphClassifier, it says "imoptr".

Hope this helps.

Cheers

Thiago

**Comment by UnravelSports** [comment]
Hi @ThiagoBorges81, very good eye! I've fixed it, thank you.

If you find anything else, feel free to let me know.
